// frontend/src/components/layout/Navbar.vue
<template>
  <nav class="bg-black text-white px-6 py-4 flex justify-between items-center border-b border-gray-800">
    <div class="text-2xl font-bold tracking-wider">
      <router-link to="/">GRAS Restaurant</router-link>
    </div>
    
    <div class="hidden md:flex space-x-8 items-center">
      <router-link to="/" class="hover:text-premium-gold transition-colors">Home</router-link>
      <router-link to="/menu" class="hover:text-premium-gold transition-colors">Menu</router-link>
      <router-link to="/gallery" class="hover:text-premium-gold transition-colors">Gallery</router-link>
      <router-link to="/contact" class="hover:text-premium-gold transition-colors">Contact</router-link>
      
      <PrimaryButton @click="$router.push('/reservation')">Book Now</PrimaryButton>
    </div>
    
    <!-- Mobile menu placeholder -->
    <div class="md:hidden">
      <button class="text-premium-gold">☰</button>
    </div>
  </nav>
</template>

<script setup>
import PrimaryButton from '../common/PrimaryButton.vue'
</script>

// frontend/src/components/Navbar.tsx
"use client";

import React, { useState, useEffect } from "react";
import Link from "next/link";
import { usePathname } from "next/navigation";
import { motion, AnimatePresence } from "framer-motion";
import { Menu, X } from "lucide-react";

const Navbar = () => {
  const [isOpen, setIsOpen] = useState(false);
  const [scrolled, setScrolled] = useState(false);
  const pathname = usePathname();

  useEffect(() => {
    const handleScroll = () => {
      setScrolled(window.scrollY > 20);
    };
    window.addEventListener("scroll", handleScroll);
    return () => window.removeEventListener("scroll", handleScroll);
  }, []);

  const navLinks = [
    { name: "Home", href: "/" },
    { name: "Menu", href: "/menu" },
    { name: "Gallery", href: "/gallery" },
    { name: "Reservations", href: "/reservations" },
    { name: "Contact", href: "/contact" },
  ];

  return (
    <nav
      className={`fixed top-0 left-0 right-0 z-50 transition-all duration-300 ${
        scrolled ? "bg-black/80 backdrop-blur-md py-4 border-b border-white/10" : "bg-transparent py-6"
      }`}
    >
      <div className="container mx-auto px-6 flex items-center justify-between">
        {/* Logo */}
        <Link href="/" className="flex items-center gap-2 group">
          <div className="w-12 h-12 rounded-full bg-primary flex items-center justify-center overflow-hidden transition-transform group-hover:scale-105">
            <span className="text-black font-bold text-xl">G</span>
          </div>
          <span className="text-white font-bold text-2xl tracking-tighter hidden sm:block">GRAS</span>
        </Link>

        {/* Desktop Links */}
        <div className="hidden md:flex items-center gap-8">
          {navLinks.map((link) => (
            <Link
              key={link.name}
              href={link.href}
              className={`relative text-sm font-medium transition-colors hover:text-primary ${
                pathname === link.href ? "text-primary" : "text-white/70"
              }`}
            >
              {link.name}
              {pathname === link.href && (
                <motion.div
                  layoutId="nav-underline"
                  className="absolute -bottom-1 left-0 right-0 h-0.5 bg-primary"
                />
              )}
            </Link>
          ))}
        </div>

        {/* Book Now Button */}
        <div className="hidden md:block">
          <Link
            href="/reservations"
            className="px-6 py-2 border border-primary text-primary rounded-full text-sm font-bold hover:bg-primary hover:text-black transition-all duration-300"
          >
            Book Now
          </Link>
        </div>

        {/* Mobile Toggle */}
        <button
          className="md:hidden text-white p-2"
          onClick={() => setIsOpen(!isOpen)}
        >
          {isOpen ? <X size={24} /> : <Menu size={24} />}
        </button>
      </div>

      {/* Mobile Menu */}
      <AnimatePresence>
        {isOpen && (
          <motion.div
            initial={{ opacity: 0, y: -20 }}
            animate={{ opacity: 1, y: 0 }}
            exit={{ opacity: 0, y: -20 }}
            className="absolute top-full left-0 right-0 bg-black border-b border-white/10 p-6 md:hidden"
          >
            <div className="flex flex-col gap-4">
              {navLinks.map((link) => (
                <Link
                  key={link.name}
                  href={link.href}
                  onClick={() => setIsOpen(false)}
                  className={`text-lg font-medium ${
                    pathname === link.href ? "text-primary" : "text-white/70"
                  }`}
                >
                  {link.name}
                </Link>
              ))}
              <Link
                href="/reservations"
                onClick={() => setIsOpen(false)}
                className="mt-4 w-full py-3 bg-primary text-black rounded-full text-center font-bold"
              >
                Book Now
              </Link>
            </div>
          </motion.div>
        )}
      </AnimatePresence>
    </nav>
  );
};

export default Navbar;
